version: '3'

volumes:
    db_data:

services:
    postgres:
        container_name: postgres
        image: postgres:15.1
        environment:
            POSTGRES_USER: dbadmin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test_db
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data   
